### ISSUE TITLE
FRMS-coe-startup-lib - remove channel feature

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [tazama-lf/frms-coe-startup-lib#31]
## User Story

**As a** Tazama system operator
**I want** to remove the channel feature
**so that** the system is as simple as possible to maintain and configure for an inexperienced user; and
**so that** the system performs as fast as possible at the lowest possible cost

**Impact assessment** required to determine if this repository is impacted by removing the channel feature (found in a search of code)

## Acceptance Criteria
1. Implement an FRMS-coe-lib version bump
2. Tests via integration testing
3. Push to dev branch/main branch and publish the package as a new release version in the main branch
4. Create/Update the documentation

**Comment by rtkay123** [comment]
Self assigned. I need to test CRSP. And we need this updated to be able to serialise the updated protofile

**Comment by rtkay123** [comment]
Tracking on this branch: https://github.com/frmscoe/frms-coe-startup-lib/tree/bump/coe-lib

**Comment by Sandy-at-Tazama** [comment]
readme.md change to remove references to crsp to be fixed in #76
